"""
URL configuration for API endpoints.
API端点的URL配置

Maps URLs to views according to the integration specification.
按照集成规范将URL映射到视图
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

# 创建DRF路由器 (Create DRF router)
router = DefaultRouter()
router.register(r"institutions", views.InstitutionViewSet, basename="institution")
router.register(r"filings", views.FilingViewSet, basename="filing")

# URL模式 (URL patterns)
urlpatterns = [
    # DRF路由器生成的URL (URLs generated by DRF router)
    path("", include(router.urls)),
    # Dashboard endpoints (仪表盘端点)
    path("dashboard/summary", views.dashboard_summary, name="dashboard-summary"),
    # Institution details (机构详情)
    # 注意：这个路由会被router的retrieve覆盖，所以使用不同的路径
    # path('institutions/<uuid:institution_id>/', views.institution_detail, name='institution-detail'),
    # Admin endpoints (管理端点)
    path("admin/companies", views.admin_companies, name="admin-companies"),
    path("admin/companies/add", views.admin_add_company, name="admin-add-company"),
    path(
        "admin/companies/<uuid:company_id>",
        views.admin_delete_company,
        name="admin-delete-company",
    ),
    path("admin/system-status", views.admin_system_status, name="admin-system-status"),
    # Crawler endpoints (爬虫端点)
    path("crawler/trigger", views.crawler_trigger, name="crawler-trigger"),
    path("crawler/status/<str:task_id>", views.crawler_status, name="crawler-status"),
]
