# Generated by Django 5.2.10 on 2026-02-02 07:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="日志ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "成功"),
                            ("ERROR", "失败"),
                            ("RUNNING", "运行中"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "filings_processed",
                    models.IntegerField(default=0, verbose_name="处理的文件数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Celery任务ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
            ],
            options={
                "verbose_name": "爬虫日志",
                "verbose_name_plural": "爬虫日志列表",
                "db_table": "crawl_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="机构ID",
                    ),
                ),
                (
                    "cik",
                    models.CharField(
                        db_index=True,
                        help_text="SEC Central Index Key，10位数字",
                        max_length=10,
                        unique=True,
                        verbose_name="CIK编号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如: Berkshire Hathaway",
                        max_length=255,
                        verbose_name="机构名称",
                    ),
                ),
                (
                    "avatar_initials",
                    models.CharField(
                        blank=True,
                        help_text="前端展示用的缩写，例如: BH",
                        max_length=3,
                        verbose_name="缩写",
                    ),
                ),
                (
                    "aum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Assets Under Management (AUM)",
                        max_digits=20,
                        null=True,
                        verbose_name="资产管理规模",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否在监控列表中",
                        verbose_name="是否激活",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "机构",
                "verbose_name_plural": "机构列表",
                "db_table": "institutions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="文件ID",
                    ),
                ),
                (
                    "period_of_report",
                    models.DateField(
                        help_text="例如: 2024-12-31", verbose_name="报告期截止日"
                    ),
                ),
                (
                    "filing_date",
                    models.DateField(
                        help_text="文件提交给SEC的日期", verbose_name="实际提交日"
                    ),
                ),
                (
                    "accession_number",
                    models.CharField(
                        help_text="SEC唯一文件编号，用于去重",
                        max_length=50,
                        unique=True,
                        verbose_name="文件编号",
                    ),
                ),
                (
                    "quarter",
                    models.CharField(
                        help_text="例如: Q4 2024", max_length=10, verbose_name="季度"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filings",
                        to="crawler.institution",
                        verbose_name="所属机构",
                    ),
                ),
            ],
            options={
                "verbose_name": "申报文件",
                "verbose_name_plural": "申报文件列表",
                "db_table": "filings",
                "ordering": ["-period_of_report", "-filing_date"],
            },
        ),
        migrations.CreateModel(
            name="OptionPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="期权ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20, verbose_name="股票代码")),
                (
                    "option_type",
                    models.CharField(
                        choices=[("CALL", "看涨期权"), ("PUT", "看跌期权")],
                        max_length=4,
                        verbose_name="期权类型",
                    ),
                ),
                (
                    "contracts",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="合约数量",
                    ),
                ),
                (
                    "notional_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="单位: 美元",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="名义价值",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "filing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_positions",
                        to="crawler.filing",
                        verbose_name="所属申报文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "期权持仓",
                "verbose_name_plural": "期权持仓列表",
                "db_table": "option_positions",
                "ordering": ["-notional_value"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="持仓ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        db_index=True,
                        help_text="例如: AAPL",
                        max_length=20,
                        verbose_name="股票代码",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="公司名称"),
                ),
                (
                    "cusip",
                    models.CharField(
                        help_text="9位证券识别码",
                        max_length=9,
                        verbose_name="CUSIP代码",
                    ),
                ),
                (
                    "share_count",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="持股数量",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="单位: 美元",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="市值",
                    ),
                ),
                (
                    "pct_portfolio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="占投资组合的百分比",
                        max_digits=5,
                        null=True,
                        verbose_name="仓位占比",
                    ),
                ),
                (
                    "share_change",
                    models.BigIntegerField(
                        blank=True,
                        help_text="较上季度变动股数",
                        null=True,
                        verbose_name="股数变动",
                    ),
                ),
                (
                    "pct_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="较上季度变动百分比",
                        max_digits=10,
                        null=True,
                        verbose_name="变动百分比",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "新建仓"),
                            ("Buy", "加仓"),
                            ("Sell", "减仓"),
                            ("Sold Out", "清仓"),
                            ("Hold", "持有"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "filing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="crawler.filing",
                        verbose_name="所属申报文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "持仓明细",
                "verbose_name_plural": "持仓明细列表",
                "db_table": "holdings",
                "ordering": ["-value"],
                "indexes": [
                    models.Index(
                        fields=["filing", "ticker"], name="holdings_filing__72c5cf_idx"
                    ),
                    models.Index(fields=["ticker"], name="holdings_ticker_08d63f_idx"),
                    models.Index(
                        fields=["action_type"], name="holdings_action__0e9bdc_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="filing",
            index=models.Index(
                fields=["institution", "-period_of_report"],
                name="filings_institu_b85413_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="filing",
            index=models.Index(
                fields=["accession_number"], name="filings_accessi_71aa4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionposition",
            index=models.Index(
                fields=["filing", "option_type"], name="option_posi_filing__d8eade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="optionposition",
            index=models.Index(fields=["ticker"], name="option_posi_ticker_f7ace1_idx"),
        ),
    ]
